[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.111.0"
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/test-ad"
  to = "/test-ad/"
  status = 301
  force = true

[[redirects]]
  from = "/test-ad/*"
  to = "/test-ad/index.html"
  status = 200
  force = true

[context.production]
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.125.7"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing.dns]
  # A Records
  [[build.processing.dns.a]]
    name = "@"
    ttl = 600  # Lower TTL for faster propagation
    values = ["75.2.60.5"]
  [[build.processing.dns.a]]
    name = "@"
    ttl = 600
    values = ["99.83.190.102"]  # Correct Netlify IP

  # CNAME Records
  [[build.processing.dns.cname]]
    name = "www"
    ttl = 600
    value = "calm-capybara-449aa9.netlify.app"  # Your Netlify app name

[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/test-ad/*"
    [headers.values]
    Cache-Control = "no-store"
    X-Robots-Tag = "all"
